
# constants
`X-Kite-Version` = "3"

#HTTP Response
STATUS_OK = "success"

# Invervals
VALID_INTERVALS = c("day","minute","3minute","5minute","10minute","15minute",
                    "30minute","60minute")

# Products
PRODUCT_MIS = "MIS"
PRODUCT_CNC = "CNC"
PRODUCT_NRML = "NRML"
PRODUCT_CO = "CO"
PRODUCT_BO = "BO"
VALID_PRODUCTS = c(PRODUCT_MIS,PRODUCT_CNC,PRODUCT_NRML,PRODUCT_CO,PRODUCT_BO)

# Order types
ORDER_TYPE_MARKET = "MARKET"
ORDER_TYPE_LIMIT = "LIMIT"
ORDER_TYPE_SLM = "SL-M"
ORDER_TYPE_SL = "SL"
VALID_ORDERS = c(ORDER_TYPE_MARKET,ORDER_TYPE_LIMIT,ORDER_TYPE_SLM,
                 ORDER_TYPE_SL)

# Varities
VARIETY_REGULAR = "regular"
VARIETY_BO = "bo"
VARIETY_CO = "co"
VARIETY_AMO = "amo"
VALID_VARIETY = c(VARIETY_REGULAR,VARIETY_BO,VARIETY_CO,VARIETY_AMO)

# Transaction type
TRANSACTION_TYPE_BUY = "BUY"
TRANSACTION_TYPE_SELL = "SELL"
VALID_TRANSACTION_TYPE = c(TRANSACTION_TYPE_BUY,TRANSACTION_TYPE_SELL)

# Validity
VALIDITY_DAY = "DAY"
VALIDITY_IOC = "IOC"
VALID_ORDER_VALIDITY = c(VALIDITY_DAY,VALIDITY_IOC)

# Exchanges
EXCHANGE_NSE = "NSE"
EXCHANGE_BSE = "BSE"
EXCHANGE_NFO = "NFO"
EXCHANGE_CDS = "CDS"
EXCHANGE_BFO = "BFO"
EXCHANGE_MCX = "MCX"
VALID_EXCHANGE = c(EXCHANGE_NSE,EXCHANGE_BSE,EXCHANGE_NFO,EXCHANGE_CDS,
                   EXCHANGE_BFO,EXCHANGE_MCX)

# Margins segments
MARGIN_EQUITY = "equity"
MARGIN_COMMODITY = "commodity"
VALID_SEGMENT = c(MARGIN_EQUITY,MARGIN_COMMODITY)

# Status constants
STATUS_COMPLETE = "COMPLETE"
STATUS_REJECTED = "REJECTED"
STATUS_CANCELLED = "CANCELLED"
VALID_ORDER_STATUS = c(STATUS_COMPLETE,STATUS_REJECTED,STATUS_CANCELLED)

# content types
VALID_CONTENT_TYPE = c("application/json","application/csv","text/csv")
